name: Install with cache

on:
  push:

permissions:
  contents: read

jobs:
  release:
    name: Build Tuist App
    runs-on: macos-15
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.1.5
          experimental: true
        env:
          MISE_HTTP_TIMEOUT: 300
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .build
          key: ${{ runner.os }}-v1-${{ hashFiles('*/Package.resolved') }}
          restore-keys: .build
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: mise run install
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            .build
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
